INSERT INTO public."STUDENT_TEAM" (name) VALUES
    ('Team Alpha'),
    ('Team Bravo'),
    ('Team Charlie'),
    ('Team Delta'),
    ('Team Echo'),
    ('Team Foxtrot'),
    ('Team Golf'),
    ('Team Hotel'),
    ('Team India'),
    ('Team Juliet');

INSERT INTO public."RECRUITMENT_ROUND" (deadline, semester, year, student_team_id, status) VALUES
    ('2023-06-30 23:59:59+00', 1, 2023, 1, 'A'),
    ('2023-12-31 23:59:59+00', 2, 2023, 2, 'I'),
    ('2024-06-30 23:59:59+00', 1, 2024, 3, 'A'),
    ('2024-12-31 23:59:59+00', 2, 2024, 4, 'I'),
    ('2025-06-30 23:59:59+00', 1, 2025, 5, 'A'),
    ('2025-12-31 23:59:59+00', 2, 2025, 6, 'I'),
    ('2026-06-30 23:59:59+00', 1, 2026, 7, 'A'),
    ('2026-12-31 23:59:59+00', 2, 2026, 8, 'I'),
    ('2027-06-30 23:59:59+00', 1, 2027, 9, 'A'),
    ('2027-12-31 23:59:59+00', 2, 2027, 10, 'I');

INSERT INTO public."OPENING" (recruitment_round_ID, title, description, app_role, status, required_skills, desired_skills) VALUES
    (1, 'Software Engineer', 'Develop and maintain software applications', 'Engineer', 'A', '{"Python", "Java", "SQL"}', '{"Docker", "AWS"}'),
    (2, 'Data Analyst', 'Analyze and interpret data', 'Analyst', 'I', '{"SQL", "R", "Python"}', '{"Tableau", "PowerBI"}'),
    (3, 'UI/UX Designer', 'Design and improve user interfaces', 'Writer', 'A', '{"Adobe XD", "Figma", "HTML/CSS"}', '{"JavaScript", "React"}'),
    (4, 'DevOps Engineer', 'Manage and automate software deployment', 'Scientist', 'I', '{"Linux", "Docker", "Kubernetes"}', '{"AWS", "Terraform"}'),
    (5, 'Data Scientist', 'Build and deploy machine learning models', 'Scientist', 'A', '{"Python", "SQL", "ML Algorithms"}', '{"TensorFlow", "PyTorch"}'),
    (6, 'Product Manager', 'Manage and prioritize product features', 'Manager', 'I', '{"Agile", "Product Strategy", "Communication"}', '{"SQL", "Python"}'),
    (7, 'Full Stack Developer', 'Develop and maintain web applications', 'Scientist', 'A', '{"JavaScript", "React", "Node.js"}', '{"AWS", "Docker"}'),
    (8, 'Cybersecurity Analyst', 'Analyze and mitigate security threats', 'Scientist', 'I', '{"Linux", "Networking", "Security Tools"}', '{"Python", "AWS"}'),
    (9, 'Mobile App Developer', 'Develop and maintain mobile applications', 'Analyst', 'A', '{"Java", "Kotlin", "Swift"}', '{"React Native", "Flutter"}'),
    (10, 'Technical Writer', 'Create and maintain technical documentation', 'Analyst', 'I', '{"Markdown", "Technical Writing", "Communication"}', '{"Python", "SQL"}'),
    (1, 'Backend Developer', 'Design and implement server-side logic', 'Analyst', 'A', '{"Python", "Django", "SQL"}', '{"AWS", "Docker"}'),
    (2, 'Business Intelligence Analyst', 'Analyze and visualize business data', 'Engineer', 'I', '{"SQL", "Power BI", "Excel"}', '{"Python", "Tableau"}'),
    (3, 'UX Researcher', 'Conduct user research and usability testing', 'Researcher', 'A', '{"User Research", "Prototyping", "Analytics"}', '{"Python", "SQL"}'),
    (4, 'Cloud Engineer', 'Design and implement cloud infrastructure', 'Researcher', 'I', '{"AWS", "Terraform", "Python"}', '{"Kubernetes", "Docker"}'),
    (5, 'Machine Learning Engineer', 'Build and deploy machine learning models', 'Researcher', 'A', '{"Python", "TensorFlow", "Keras"}', '{"AWS", "Docker"}'),
    (6, 'Scrum Master', 'Facilitate and lead Agile development', 'Researcher', 'I', '{"Agile", "Scrum", "Project Management"}', '{"Jira", "Confluence"}'),
    (7, 'Front-end Developer', 'Develop and maintain user interfaces', 'Manager', 'A', '{"JavaScript", "React", "CSS"}', '{"TypeScript", "Redux"}'),
    (8, 'Penetration Tester', 'Identify and exploit security vulnerabilities', 'Analyst', 'I', '{"Ethical Hacking", "Networking", "Linux"}', '{"Python", "Metasploit"}'),
    (9, 'iOS Developer', 'Develop and maintain iOS applications', 'Consultant', 'A', '{"Swift", "Xcode", "iOS SDK"}', '{"SwiftUI", "ARKit"}'),
    (10, 'Technical Content Writer', 'Create and maintain technical documentation', 'Writer', 'I', '{"Markdown", "Technical Writing", "Communication"}', '{"HTML", "CSS"}'),
    (1, 'DevOps Engineer', 'Automate deployment and infrastructure management', 'Writer', 'A', '{"AWS", "Kubernetes", "Terraform"}', '{"Python", "Ansible"}'),
    (2, 'Data Visualization Specialist', 'Create visual representations of data', 'Writer', 'I', '{"Tableau", "D3.js", "Data Analysis"}', '{"Python", "R"}'),
    (3, 'UI Designer', 'Design visually appealing user interfaces', 'Designer', 'A', '{"Adobe XD", "Figma", "UI Design"}', '{"Motion Design", "Illustration"}'),
    (4, 'Site Reliability Engineer', 'Ensure system reliability and availability', 'Engineer', 'I', '{"Linux", "Monitoring", "Automation"}', '{"Python", "Kubernetes"}'),
    (5, 'Natural Language Processing Engineer', 'Build and deploy NLP models', 'Engineer', 'A', '{"Python", "NLTK", "Spacy"}', '{"TensorFlow", "Hugging Face"}'),
    (6, 'Agile Coach', 'Mentor and coach teams in Agile practices', 'Coach', 'I', '{"Agile", "Coaching", "Facilitation"}', '{"Scrum", "Kanban"}'),
    (7, 'React Native Developer', 'Develop cross-platform mobile applications', 'Engineer', 'A', '{"React Native", "JavaScript", "Mobile Development"}', '{"Redux", "Firebase"}'),
    (8, 'Cybersecurity Consultant', 'Assess and improve security posture', 'Consultant', 'I', '{"Security Standards", "Risk Management", "Compliance"}', '{"Cloud Security", "DevSecOps"}'),
    (9, 'Android Developer', 'Develop and maintain Android applications', 'Engineer', 'A', '{"Java", "Kotlin", "Android SDK"}', '{"Jetpack Compose", "Flutter"}'),
    (10, 'API Developer', 'Design and implement RESTful APIs', 'Engineer', 'I', '{"RESTful APIs", "API Design", "API Testing"}', '{"GraphQL", "Microservices"}');

INSERT INTO public."APPLICATION" (opening_id, email, name, phone, semesters_until_completion, current_semester, course_enrolled, major_enrolled, cover_letter, skills, accepted) VALUES
    (1, 'john@example.com', 'John Doe', '1234567890', 2, 6, 'Computer Science', 'Computer Science', 'I am a passionate software engineer with experience in Python and Java.', '{"Python", "Java", "SQL"}', 'U'),
    (2, 'jane@example.com', 'Jane Smith', '9876543210', 4, 2, 'Business Analytics', 'Business Analytics', 'I have strong skills in data analysis and visualization using SQL and R.', '{"SQL", "R", "Python"}', 'U'),
    (3, 'bob@example.com', 'Bob Johnson', '5555555555', 6, 2, 'Design', 'Graphic Design', 'I am a creative UI/UX designer with experience in Adobe XD and Figma.', '{"Adobe XD", "Figma", "HTML/CSS"}', 'U'),
    (4, 'alice@example.com', 'Alice Lee', '1112223333', 3, 5, 'Computer Science', 'Computer Science', 'I have experience in DevOps and cloud computing using AWS and Kubernetes.', '{"Linux", "Docker", "Kubernetes"}', 'U'),
    (5, 'tom@example.com', 'Tom Wilson', '4445556666', 1, 7, 'Data Science', 'Data Science', 'I am a data scientist with expertise in machine learning algorithms and Python.', '{"Python", "SQL", "ML Algorithms"}', 'U'),
    (6, 'sara@example.com', 'Sara Davis', '7778889999', 5, 3, 'Business Administration', 'Business Administration', 'I have strong communication and project management skills using Agile methodologies.', '{"Agile", "Product Strategy", "Communication"}', 'U'),
    (7, 'mike@example.com', 'Mike Brown', '2223334444', 2, 6, 'Computer Science', 'Computer Science', 'I am a full stack developer with experience in JavaScript, React, and Node.js.', '{"JavaScript", "React", "Node.js"}', 'U'),
    (8, 'emily@example.com', 'Emily Taylor', '6667778888', 4, 4, 'Cybersecurity', 'Cybersecurity', 'I have experience in network security and threat analysis using various security tools.', '{"Linux", "Networking", "Security Tools"}', 'U'),
    (9, 'david@example.com', 'David Anderson', '9990009999', 3, 5, 'Computer Science', 'Computer Science', 'I am a mobile app developer with experience in Java, Kotlin, and Swift.', '{"Java", "Kotlin", "Swift"}', 'U'),
    (10, 'sophia@example.com', 'Sophia Martinez', '8887776666', 6, 2, 'Technical Communication', 'Technical Communication', 'I am a technical writer with expertise in creating clear and concise documentation.', '{"Markdown", "Technical Writing", "Communication"}', 'U'),
    (1, 'alex@example.com', 'Alex Johnson', '5551234567', 3, 5, 'Computer Science', 'Computer Science', 'I have experience in Python and Django for building web applications.', '{"Python", "Django", "SQL"}', 'U'),
    (2, 'emma@example.com', 'Emma Davis', '7778889999', 2, 6, 'Business Analytics', 'Business Analytics', 'I am skilled in data analysis and visualization using Power BI and Excel.', '{"SQL", "Power BI", "Excel"}', 'U'),
    (3, 'michael@example.com', 'Michael Wilson', '1234567890', 4, 4, 'Human-Computer Interaction', 'Human-Computer Interaction', 'I have a strong background in user research and usability testing.', '{"User Research", "Prototyping", "Analytics"}', 'U'),
    (4, 'olivia@example.com', 'Olivia Martinez', '9876543210', 5, 3, 'Computer Science', 'Computer Science', 'I have experience in AWS cloud infrastructure and Terraform.', '{"AWS", "Terraform", "Python"}', 'U'),
    (5, 'william@example.com', 'William Brown', '5555555555', 2, 6, 'Data Science', 'Data Science', 'I have expertise in building and deploying machine learning models using TensorFlow.', '{"Python", "TensorFlow", "Keras"}', 'U'),
    (6, 'sophia@example.com', 'Sophia Taylor', '1112223333', 6, 2, 'Business Administration', 'Business Administration', 'I have strong project management and Agile facilitation skills.', '{"Agile", "Scrum", "Project Management"}', 'U'),
    (7, 'james@example.com', 'James Anderson', '4445556666', 3, 5, 'Computer Science', 'Computer Science', 'I am a skilled front-end developer with experience in React and CSS.', '{"JavaScript", "React", "CSS"}', 'U'),
    (8, 'ava@example.com', 'Ava Garcia', '7778889999', 4, 4, 'Cybersecurity', 'Cybersecurity', 'I have experience in ethical hacking and penetration testing.', '{"Ethical Hacking", "Networking", "Linux"}', 'U'),
    (9, 'benjamin@example.com', 'Benjamin Rodriguez', '2223334444', 2, 6, 'Computer Science', 'Computer Science', 'I am an iOS developer with expertise in Swift and Xcode.', '{"Swift", "Xcode", "iOS SDK"}', 'U'),
    (10, 'isabella@example.com', 'Isabella Hernandez', '6667778888', 5, 3, 'Technical Communication', 'Technical Communication', 'I have excellent technical writing and communication skills.', '{"Markdown", "Technical Writing", "Communication"}', 'U'),
    (1, 'henry@example.com', 'Henry Gonzalez', '9990009999', 3, 5, 'Computer Science', 'Computer Science', 'I have experience in DevOps and infrastructure automation using AWS and Kubernetes.', '{"AWS", "Kubernetes", "Terraform"}', 'U'),
    (2, 'mia@example.com', 'Mia Perez', '8887776666', 4, 4, 'Business Analytics', 'Business Analytics', 'I am skilled in data visualization using Tableau and D3.js.', '{"Tableau", "D3.js", "Data Analysis"}', 'U'),
    (3, 'jacob@example.com', 'Jacob Sanchez', '1234567890', 6, 2, 'Design', 'Graphic Design', 'I have expertise in UI design using Adobe XD and Figma.', '{"Adobe XD", "Figma", "UI Design"}', 'U'),
    (4, 'abigail@example.com', 'Abigail Ramirez', '9876543210', 2, 6, 'Computer Science', 'Computer Science', 'I have experience in site reliability engineering and monitoring systems.', '{"Linux", "Monitoring", "Automation"}', 'U'),
    (5, 'daniel@example.com', 'Daniel Torres', '5555555555', 3, 5, 'Data Science', 'Data Science', 'I have expertise in natural language processing and building NLP models.', '{"Python", "NLTK", "Spacy"}', 'U'),
    (6, 'emily@example.com', 'Emily Rivera', '1112223333', 4, 4, 'Business Administration', 'Business Administration', 'I am an experienced Agile coach and facilitator.', '{"Agile", "Coaching", "Facilitation"}', 'U'),
    (7, 'matthew@example.com', 'Matthew Gomez', '4445556666', 5, 3, 'Computer Science', 'Computer Science', 'I am a skilled React Native developer with experience in mobile app development.', '{"React Native", "JavaScript", "Mobile Development"}', 'U'),
    (8, 'avery@example.com', 'Avery Diaz', '7778889999', 6, 2, 'Cybersecurity', 'Cybersecurity', 'I have experience in cybersecurity consulting and risk management.', '{"Security Standards", "Risk Management", "Compliance"}', 'U'),
    (9, 'joseph@example.com', 'Joseph Reyes', '2223334444', 2, 6, 'Computer Science', 'Computer Science', 'I am an Android developer with expertise in Java and Kotlin.', '{"Java", "Kotlin", "Android SDK"}', 'U'),
    (10, 'hannah@example.com', 'Hannah Morales', '6667778888', 3, 5, 'Computer Science', 'Computer Science', 'I have experience in designing and implementing RESTful APIs.', '{"RESTful APIs", "API Design", "API Testing"}', 'U');