create table
  public."USER" (
    id bigint generated by default as identity,
    email character varying not null,
    role character varying not null,
    student_team_id bigint not null,
    name character varying null,
    constraint USER_pkey primary key (id, email),
    constraint USER_id_fkey foreign key (id) references "STUDENT_TEAM" (id)
  ) tablespace pg_default;

create table
  public."STUDENT_TEAM" (
    id bigint generated by default as identity,
    name character varying not null,
    constraint STUDENT_TEAM_pkey primary key (id),
    constraint STUDENT_TEAM_name_key unique (name)
  ) tablespace pg_default;

create table
  public."RECRUITMENT_ROUND" (
    id bigint generated by default as identity,
    semester character varying not null,
    year date not null,
    student_team_id bigint not null,
    status character varying not null,
    constraint RECRUITMENT_ROUND_pkey primary key (id, semester, year, student_team_id),
    constraint RECRUITMENT_ROUND_id_key unique (id),
    constraint RECRUITMENT_ROUND_student_team_id_fkey foreign key (student_team_id) references "STUDENT_TEAM" (id)
  ) tablespace pg_default;

create table
  public."OPENING" (
    id bigint generated by default as identity,
    "recruitment_round_ID" bigint not null,
    title character varying not null,
    description character varying null,
    app_role character varying not null,
    status character varying not null,
    required_skills character varying[] not null,
    desired_skills character varying[] null,
    constraint OPENING_pkey primary key (id, "recruitment_round_ID", app_role),
    constraint OPENING_id_key unique (id),
    constraint OPENING_recruitment_round_ID_fkey foreign key ("recruitment_round_ID") references "RECRUITMENT_ROUND" (id)
  ) tablespace pg_default;

create table
  public."APPLICATION" (
    id bigint generated by default as identity,
    opening_id bigint not null,
    email character varying not null,
    name character varying not null,
    phone character varying not null,
    semesters_until_completion integer not null,
    current_semester integer not null,
    course_enrolled character varying not null,
    major_enrolled character varying null,
    cover_letter text null,
    skills character varying[] not null,
    constraint APPLICATION_pkey primary key (id, opening_id, email),
    constraint APPLICATION_opening_id_fkey foreign key (opening_id) references "OPENING" (id)
  ) tablespace pg_default;