DROP TABLE IF EXISTS public."APPLICATION" CASCADE;
DROP TABLE IF EXISTS public."OPENING" CASCADE;
DROP TABLE IF EXISTS public."STUDENT_TEAM" CASCADE;
DROP TABLE IF EXISTS public."USER" CASCADE;
DROP TABLE IF EXISTS public."RECRUITMENT_ROUND" CASCADE;

CREATE TABLE public."STUDENT_TEAM" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    CONSTRAINT STUDENT_TEAM_pkey PRIMARY KEY (id),
    CONSTRAINT STUDENT_TEAM_name_key UNIQUE (name)
) TABLESPACE pg_default;

-- CREATE TABLE public."USER" (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--     email VARCHAR NOT NULL,
--     role VARCHAR NOT NULL,
--     student_team_id BIGINT NOT NULL,
--     name VARCHAR NULL,
--     CONSTRAINT USER_pkey PRIMARY KEY (id),
--     CONSTRAINT USER_unique UNIQUE (email),
--     CONSTRAINT USER_student_team_id_fkey FOREIGN KEY (student_team_id) REFERENCES "STUDENT_TEAM" (id)
-- ) TABLESPACE pg_default;

CREATE TABLE public."RECRUITMENT_ROUND" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deadline TIMESTAMP WITH TIME ZONE NOT NULL,
    semester VARCHAR NOT NULL,
    year BIGINT NOT NULL,
    student_team_id BIGINT NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'I' CHECK (status IN ('A', 'I')),
    CONSTRAINT RECRUITMENT_ROUND_pkey PRIMARY KEY (id),
    CONSTRAINT RECRUITMENT_ROUND_unique UNIQUE (semester, year, student_team_id),
    CONSTRAINT RECRUITMENT_ROUND_student_team_id_fkey FOREIGN KEY (student_team_id) REFERENCES "STUDENT_TEAM" (id)
) TABLESPACE pg_default;

CREATE TABLE public."OPENING" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recruitment_round_ID BIGINT NOT NULL,
    title VARCHAR NOT NULL,
    description VARCHAR NULL,
    status VARCHAR NOT NULL DEFAULT 'I' CHECK (status IN ('A', 'I')),
    required_skills VARCHAR[] NOT NULL,
    desired_skills VARCHAR[] NULL,
    CONSTRAINT OPENING_pkey PRIMARY KEY (id),
    CONSTRAINT OPENING_unique UNIQUE (recruitment_round_ID, title),
    CONSTRAINT OPENING_recruitment_round_ID_fkey FOREIGN KEY (recruitment_round_ID) REFERENCES "RECRUITMENT_ROUND" (id)
) TABLESPACE pg_default;

CREATE TABLE public."APPLICATION" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    opening_id BIGINT NOT NULL,
    email VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    phone VARCHAR NOT NULL,
    semesters_until_completion INTEGER NOT NULL,
    current_semester INTEGER NOT NULL,
    course_enrolled VARCHAR NOT NULL,
    major_enrolled VARCHAR NULL,
    cover_letter TEXT NULL,
    skills VARCHAR[] NOT NULL,
    accepted VARCHAR NOT NULL DEFAULT 'U' CHECK (accepted IN ('A', 'R', 'U')),
    CONSTRAINT APPLICATION_pkey PRIMARY KEY (id),
    CONSTRAINT APPLICATION_unique UNIQUE (opening_id, email),
    CONSTRAINT APPLICATION_opening_id_fkey FOREIGN KEY (opening_id) REFERENCES "OPENING" (id)
) TABLESPACE pg_default;

-- +++++++++ POSTGRES FUNCTIONS +++++++++

CREATE OR REPLACE FUNCTION get_all_rec_rounds_with_openings_count()
RETURNS TABLE (
    id BIGINT,
    deadline TIMESTAMP WITH TIME ZONE,
    semester VARCHAR,
    year BIGINT,
    student_team_id BIGINT,
    status VARCHAR,
    openings_count BIGINT
)
AS $$
SELECT
    rr.id,
    rr.deadline,
    rr.semester,
    rr.year,
    rr.student_team_id,
    rr.status,
    COALESCE(oc.openings_count, 0) AS openings_count
FROM
    public."RECRUITMENT_ROUND" rr
LEFT JOIN
    (
        SELECT
            recruitment_round_ID,
            COUNT(*) AS openings_count
        FROM
            public."OPENING"
        GROUP BY
            recruitment_round_ID
    ) oc ON rr.id = oc.recruitment_round_ID;
$$ LANGUAGE SQL;