-- Add new attributes
ALTER TABLE IF EXISTS public."RECRUITMENT_ROUND"
ADD COLUMN interview_preference_deadline TIMESTAMP WITH TIME ZONE NOT NULL,
ADD COLUMN interview_period VARCHAR[];

-- Rename an existing attribute
ALTER TABLE IF EXISTS public."RECRUITMENT_ROUND"
RENAME COLUMN deadline TO application_deadline;

-- Create TEAM_LEAD_ASSIGNMENT table
CREATE TABLE public."INTERVIEWER_ASSIGNMENT" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    CONSTRAINT INTERVIEWER_ASSIGNMENT_pkey PRIMARY KEY (id),
    CONSTRAINT INTERVIEWER_ASSIGNMENT_application_id_profile_id_key UNIQUE (application_id, profile_id),
    CONSTRAINT INTERVIEWER_ASSIGNMENT_application_id_fkey FOREIGN KEY (application_id) REFERENCES "APPLICATION" (id),
    CONSTRAINT INTERVIEWER_ASSIGNMENT_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES "PROFILE" (id)
) TABLESPACE pg_default;