-- Drop APPLICATION table
DROP TABLE IF EXISTS public."APPLICATION" CASCADE;

-- Drop TEAM_LEAD_ASSIGNMENT table
DROP TABLE IF EXISTS public."TEAM_LEAD_ASSIGNMENT" CASCADE;

-- Drop OPENING table
DROP TABLE IF EXISTS public."OPENING" CASCADE;

-- Drop RECRUITMENT_ROUND table
DROP TABLE IF EXISTS public."RECRUITMENT_ROUND" CASCADE;

-- Drop PROFILE_TEAM_INFO table
DROP TABLE IF EXISTS public."PROFILE_TEAM_INFO" CASCADE;

-- Drop STUDENT_TEAM table
DROP TABLE IF EXISTS public."STUDENT_TEAM" CASCADE;

-- Drop PROFILE_TEMP table
DROP TABLE IF EXISTS public."PROFILE_TEMP" CASCADE;

-- Drop PROFILE table
DROP TABLE IF EXISTS public."PROFILE" CASCADE;

-- Create PROFILE table
CREATE TABLE public."PROFILE" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID,
    email VARCHAR NOT NULL,
    interview_availability VARCHAR[],
    CONSTRAINT PROFILE_pkey PRIMARY KEY (id),
    CONSTRAINT PROFILE_email_key UNIQUE (email),
    CONSTRAINT PROFILE_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
) TABLESPACE pg_default;

-- Create STUDENT_TEAM table
CREATE TABLE public."STUDENT_TEAM" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    description VARCHAR,
    CONSTRAINT STUDENT_TEAM_pkey PRIMARY KEY (id),
    CONSTRAINT STUDENT_TEAM_name_key UNIQUE (name)
) TABLESPACE pg_default;

-- Create PROFILE_TEAM_INFO table
CREATE TABLE public."PROFILE_TEAM_INFO" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT NOT NULL,
    student_team_id BIGINT NOT NULL,
    role VARCHAR(1) NOT NULL CHECK (role IN ('O', 'A', 'T')),
    CONSTRAINT PROFILE_TEAM_INFO_pkey PRIMARY KEY (id),
    CONSTRAINT PROFILE_TEAM_INFO_profile_id_student_team_id_key UNIQUE (profile_id, student_team_id),
    CONSTRAINT PROFILE_TEAM_INFO_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES "PROFILE" (id),
    CONSTRAINT PROFILE_TEAM_INFO_student_team_id_fkey FOREIGN KEY (student_team_id) REFERENCES "STUDENT_TEAM" (id)
) TABLESPACE pg_default;

-- Create RECRUITMENT_ROUND table
CREATE TABLE public."RECRUITMENT_ROUND" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    student_team_id BIGINT NOT NULL,
    semester VARCHAR NOT NULL,
    year BIGINT NOT NULL,
    deadline TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(1) NOT NULL DEFAULT 'I' CHECK (status IN ('A', 'I', 'R')),
    CONSTRAINT RECRUITMENT_ROUND_pkey PRIMARY KEY (id),
    CONSTRAINT RECRUITMENT_ROUND_student_team_id_semester_year_key UNIQUE (student_team_id, semester, year),
    CONSTRAINT RECRUITMENT_ROUND_student_team_id_fkey FOREIGN KEY (student_team_id) REFERENCES "STUDENT_TEAM" (id)
) TABLESPACE pg_default;

-- Create OPENING table
CREATE TABLE public."OPENING" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recruitment_round_id BIGINT NOT NULL,
    title VARCHAR NOT NULL,
    description VARCHAR,
    status VARCHAR(1) NOT NULL DEFAULT 'I' CHECK (status IN ('A', 'I', 'R')),
    required_skills VARCHAR[] NOT NULL,
    desired_skills VARCHAR[],
    task_email_format VARCHAR,
    task_enabled BOOLEAN,
    interview_allocation_status VARCHAR(1) DEFAULT 'N' CHECK (interview_allocation_status IN ('N', 'I', 'S')), 
    CONSTRAINT OPENING_pkey PRIMARY KEY (id),
    CONSTRAINT OPENING_recruitment_round_id_title_key UNIQUE (recruitment_round_id, title),
    CONSTRAINT OPENING_recruitment_round_id_fkey FOREIGN KEY (recruitment_round_id) REFERENCES "RECRUITMENT_ROUND" (id)
) TABLESPACE pg_default;

-- Create TEAM_LEAD_ASSIGNMENT table
CREATE TABLE public."TEAM_LEAD_ASSIGNMENT" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    opening_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    CONSTRAINT TEAM_LEAD_ASSIGNMENT_pkey PRIMARY KEY (id),
    CONSTRAINT TEAM_LEAD_ASSIGNMENT_opening_id_profile_id_key UNIQUE (opening_id, profile_id),
    CONSTRAINT TEAM_LEAD_ASSIGNMENT_opening_id_fkey FOREIGN KEY (opening_id) REFERENCES "OPENING" (id),
    CONSTRAINT TEAM_LEAD_ASSIGNMENT_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES "PROFILE" (id)
) TABLESPACE pg_default;

-- Create APPLICATION table
CREATE TABLE public."APPLICATION" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    opening_id BIGINT NOT NULL,
    email VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    phone VARCHAR NOT NULL,
    semesters_until_completion INTEGER NOT NULL,
    course_name VARCHAR NOT NULL,
    current_semester INTEGER NOT NULL,
    major_enrolled VARCHAR,
    additional_info TEXT,
    skills VARCHAR[] NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    candidate_availability VARCHAR[],
    interview_date TIMESTAMP WITH TIME ZONE,
    interview_notes VARCHAR,
    interview_score INTEGER,
    status VARCHAR(1) NOT NULL DEFAULT 'A' CHECK (status IN ('A', 'C', 'R', 'X')),
    profile_id BIGINT,
    CONSTRAINT APPLICATION_pkey PRIMARY KEY (id),
    CONSTRAINT APPLICATION_email_opening_id_key UNIQUE (opening_id, email),
    CONSTRAINT APPLICATION_opening_id_fkey FOREIGN KEY (opening_id) REFERENCES "OPENING" (id),
    CONSTRAINT APPLICATION_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES "PROFILE" (id)
) TABLESPACE pg_default;

